###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka        
server:
  port: 9800


  
spring:
  application:
    name: clever-shop-spike
  redis:
    host: 192.168.10.107
   # password: 123456
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
###数据库相关连接      
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clever_spike
swagger:
  base-package: com.clever.service

  